<?php

include_once('gozulla_directory.features.inc');


/**
 * Implementation of hook_perm().
 */
function gozulla_directory_perm() {
  return array('administer gozulla directory settings');
}

/*
 * Admin Settings form for gozulla directory
 */
function gozulla_directory() {
  
  $form['gozulla_directory_bad_factual_ids'] = array(
    '#type' => 'textarea',
    '#title' => t('Bad Factual ID\'s'),
    '#description' => t('Enter bad Factual ID\'s separated by commas. IDs listed here will be excluded in results'),
    '#default_value' => variable_get('gozulla_directory_bad_factual_ids', ''),
    '#required' => FALSE,
  );

  $form['gozulla_directory_factual_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Factual API key'),
    '#default_value' => variable_get('gozulla_directory_factual_key', ''),
    '#required' => TRUE
  );
  
  $form['gozulla_directory_factual_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('Factual API secret'),
    '#default_value' => variable_get('gozulla_directory_factual_secret', ''),
    '#required' => TRUE
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_menu().
 */
function gozulla_directory_menu() {
  
  $items = array();
    $items['admin/config/gozulla_directory'] = array(
      'title' => t('gozulla directory'),
      'description' => t('gozulla directory settings.'),
      'page callback' => 'drupal_get_form',
      'access callback' => TRUE,
      'page arguments' => array('gozulla_directory'),
      'access arguments' => array('administer gozulla directory settings'),
      'type' => MENU_NORMAL_ITEM,
    );

  // $items = array();
  //   $items['disc'] = array(
  //     'title' => 'Disc Golf Directory',
  //     'page callback' => 'gozulla_directory_disc',
  //     'access callback' => TRUE,
  //     'type' => MENU_CALLBACK,
  //   );
   /* $items['help'] = array(
      'title' => 'Help On The Way',
      'page callback' => 'gozulla_directory_help',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );*/
  return $items;
}


//foreach ($results as $result) {
//$options[] = $result->term_data_name;
//}

//dpm($_SESSION['ip_geoloc']);

function gozulla_directory_form_alter(&$form, &$form_state, $form_id) {
  
  if (isset($_SESSION['ip_geoloc']['location']['locality']) && isset($_SESSION['ip_geoloc']['location']['administrative_area_level_1'])) {
    $city_state = $_SESSION['ip_geoloc']['location']['locality'] . ', ' . $_SESSION['ip_geoloc']['location']['administrative_area_level_1'];
  }
  else {
    $city_state = t('Newport, OR');
  }



  //dpm($form);
  switch ($form_id) {
    
    case 'views_exposed_form':
      if ($form['#id'] == 'views-exposed-form-gozulla-directory-bike'   || 
        $form['#id'] == 'views-exposed-form-gozulla-directory-boat'     || 
        $form['#id'] == 'views-exposed-form-gozulla-directory-climb'    || 
        $form['#id'] == 'views-exposed-form-gozulla-directory-golf'     || 
        $form['#id'] == 'views-exposed-form-gozulla-directory-skate'    || 
        $form['#id'] == 'views-exposed-form-gozulla-directory-snow'     ||
        $form['#id'] == 'views-exposed-form-gozulla-directory-surf'     ||
        $form['#id'] == 'views-exposed-form-gozulla-directory-deals'    ||
        $form['#id'] == 'views-exposed-form-gozulla-directory-lodging'  ||
        $form['#id'] == 'views-exposed-form-gozulla-directory-deals-by-sport') {    




        // Using dpm with Devel installed to give me array data on the Views form
       
        $form['submit'] = array(
          '#type' => 'image_button',
          '#src' => drupal_get_path('module', 'gozulla_directory') .'/images/go_btn.png',
        );

        $form['circle']['value']['#default_value'] = 50;
        
        $form['circle']['location']['#size'] = 14; 
        $form['circle']['location']['#default_value'] = $city_state; 
        $form['circle']['location']['#field_prefix'] = '+'; 

        $form['circle']['value']['#field_prefix'] =  t('<span id="findme"><a href="#" id="findme-link">FIND ME</a></span> or search '); 
        $form['circle']['value']['#field_suffix'] = t('mi '); 
      }
      
      if ($form['#id'] == 'views-exposed-form-feed-display-combined-feed') {
        $form['tid']['#options']['All'] = t(' - all sports - ');
        //dpm($form);
      }
      
    break;

    case 'gozullalocation_node_form':
      

      // unset delete button for non-admins
      global $user;
      if (!in_array('administrator', array_values($user->roles)) && !in_array('site manager', array_values($user->roles)) ) { 
        unset($form['#groups']['group_places_id']);
        unset($form['#groups']['group_op_buttons']);
        unset($form['field_location_type']);
        unset($form['field_factual_id']['und'][0]['value']);
        unset($form['field_places_id']['und'][0]['value']);
        unset($form['field_gozulla_subscription']['und']);
        unset($form['revision_information']);
      }

      //group_places_id

      //dpm($form);
      break;
  }
}


/**
 * Implements hook_theme()
 */
/*function gozulla_directory_theme() {
  return array(
    'gozulla_directory_sport_shops' => array(
      'render element' => 'shops',
      'template'       => 'gozulla-directory-sport-shops',
      'path'           => drupal_get_path('module', 'gozulla_directory') . '/theme',
    ),
  );
}*/


// Populate the page template suggestions.
if ($suggestions = theme_get_suggestions(arg(), 'html')) {
  $variables['theme_hook_suggestions'] = $suggestions;
}


/**
 * Constructs a sports directory page.
 */
function gozulla_directory_disc() {
  return array('#markup' => '
    <ul>
      <li>
        <div id="disc-directory">' . t('disc golf directory coming soon') . '</div>
      </li>
    </ul>
    '
  );
}


/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function gozulla_directory_block_info() {

  $blocks['bike'] = array(
    // info: The name of the block.
    //$view = views_get_view('gozulla_directory');
    //$view->set_display('bike');
    //$view->is_cacheable = FALSE;  
    //$view->execute();  
    //dpm($view->exposed_raw_input);


//     $view = views_get_view('gozulla_directory')
//     ->set_display('defaults');
//     ->set_items_per_page(0);
//     ->execute();
// $results = $view->result;
//     views_get_view('');
    'info' => t('gozulla: bike shops (factual places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'bike',
  );
  
  $blocks['boat'] = array(
    // info: The name of the block.
    'info' => t('gozulla: boat shops (factual places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'boat',
  );

  $blocks['climb'] = array(
    // info: The name of the block.
    'info' => t('gozulla: climb shops (factual places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'climb',
  );  
  
  $blocks['golf'] = array(
    // info: The name of the block.
    'info' => t('gozulla: golf shops (factual places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'golf',
  );
  
  $blocks['skate'] = array(
    // info: The name of the block.
    'info' => t('gozulla: skate shops (factual places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'skate',
  );
  
  $blocks['snow'] = array(
    // info: The name of the block.
    'info' => t('gozulla: snow shops (factual places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'snow',
  );
  
  $blocks['surf'] = array(
    // info: The name of the block.
    'info' => t('gozulla: surf shops (factual places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'surf',
  );

  $blocks['lodging'] = array(
    // info: The name of the block.
    'info' => t('gozulla: lodging (factual places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'lodging',
  );

  return $blocks;

}




  



/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function gozulla_directory_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  $block = '';
  switch ($delta) {

    case 'bike':



      $block['subject'] = t('');
      $block['content'] = gozulla_directory_contents($delta);
      break;
      
    case 'boat':
      $block['subject'] = t('');
      $block['content'] = gozulla_directory_contents($delta);
      break;  
      
    case 'climb':
      $block['subject'] = t('');
      $block['content'] = gozulla_directory_contents($delta);
      break;

    case 'golf':
      $block['subject'] = t('');
      $block['content'] = gozulla_directory_contents($delta);
      break; 

    case 'skate':
      $block['subject'] = t('');
      $block['content'] = gozulla_directory_contents($delta);
      break;
      
    case 'snow':
      $block['subject'] = t('');
      $block['content'] = gozulla_directory_contents($delta);
      break;

    case 'surf':
      $block['subject'] = t('');
      $block['content'] = gozulla_directory_contents($delta);
      break;

    case 'lodging':
      $block['subject'] = t('');
      $block['content'] = gozulla_directory_contents($delta);
      break;  

    default:
      $block['subject'] = t('');
      $block['content'] = gozulla_directory_contents($delta);
      break;
          
  }

  return $block;

}

/**
 * A module-defined block content function.
 */
function gozulla_directory_contents($which_block) {
  //$shops = array();
  $sport = 'all';
  switch ($which_block) {
      
    case 'bike':

// $name = 'gozulla_directory';
// $display = 'bike';
// $filter0 = 'circle_op';
// $filter1 = "circle['value']";
// $filter2 = "circle['location']";
// $view = views_get_view($name);


// $view->exposed_input[$filter0] = '<';
// $view->exposed_input[$filter1] = '50';
// $view->exposed_input[$filter2] = 'Corvallis, OR';
// $view->set_display($display);
// $view->execute();
// $shopresults = $view->result;
// dpm($shopresults);

  //dpm($results);

//$form['circle']['location']['#default_value']
    // $name = 'gozulla_directory';
    // $display = 'bike';
    // $view = views_get_view($name);
    // $view->set_display($display);

// The $exposed_filters keys must correctly correspond with the actual keys of your view's exposed filters.

  //$args = array($node-> tid);
    //$sport_id = 14;
    //$args = array($sport_id);
//$view->set_arguments($args);
  //$exposed_filters = array(
    //'keys' => 'circle_op',

  //term_node_tid_depth' => 'All',
//);


// Pass in exposed filter values. array_merge() order prioritizes user input.
// $view->exposed_input = array_merge($exposed_filters, (array)$view->exposed_input);
// $view->exposed_raw_input = array_merge($exposed_filters, (array)$view->exposed_raw_input);
// $view->exposed_data = array_merge($exposed_filters, (array)$view->exposed_data);


//$output = $view->preview();
//if ($view->result) {
  //print $output;
//}

  //$view->set_items_per_page(0);
  //$view->execute();
  //$results = $view->result;

  //dpm($results);



      $sport = 'bike';
      include_once('gozulla_directory_shops.inc'); // common include
      return array('#markup' => $shops);
      break;
        
    case 'boat':
      $sport = 'boat';
      include_once('gozulla_directory_shops.inc'); // common include
      return array('#markup' => $shops);
      break; 
      
    case 'climb':
      $sport = 'climb';
      include_once('gozulla_directory_shops.inc'); // common include
      return array('#markup' => $shops);
      break;
      
    case 'golf':
      $sport = 'golf';
      include_once('gozulla_directory_shops.inc'); // common include
      return array('#markup' => $shops);
      break; 

    case 'skate':
      $sport = 'skate';
      include_once('gozulla_directory_shops.inc'); // common include
      return array('#markup' => $shops);
      break;
      
    case 'snow':
      $sport = 'snow';
      include_once('gozulla_directory_shops.inc'); // common include
      return array('#markup' => $shops);
      break; 

    case 'surf':
      $sport = 'surf';
      include_once('gozulla_directory_shops.inc'); // common include
      return array('#markup' => $shops);
      break;

    case 'lodging':
      $sport = 'lodging';
      include_once('gozulla_directory_shops.inc'); // common include
      return array('#markup' => $shops);
      break; 

    // default:
    //   $sport = 'default';
    //   include_once('gozulla_directory_shops.inc'); // common include
    //   return array('#markup' => $shops);
    //   break; 

  }

}







